services:
  backend:
    # Build from the current directory using the Multi-Stage Dockerfile
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gov-backend
    ports:
      # Expose 8080 so you can test via Postman/Browser on Windows
      - "8080:8080"
    volumes:
      # Mount your local .env (Dev Credentials)
      - ./.env:/.env
    # We remove 'restart: always' because locally you want it to stop if it crashes, so you can see the error.