/* =========================================================
   1. Independent Tables (No Foreign Keys)
   ========================================================= */

create table event_categories
(
    id               bigint generated by default as identity primary key,
    category_key     varchar(50)                 not null unique,
    name             varchar(100)                not null,
    icon             varchar(100),
    color            varchar(7),
    display_order    integer                     not null,
    is_active        boolean                     not null,
    created_at       timestamp(6) with time zone not null,
    last_modified_at timestamp(6) with time zone not null
);

create table platforms
(
    id                    uuid                        not null primary key,
    name                  varchar(100)                not null unique,
    status                varchar(20)                 not null check (status in ('ACTIVE', 'SUSPENDED', 'INACTIVE')),
    api_url               varchar(500)                not null,
    shared_secret         varchar(255)                not null,
    contact_email         varchar(255),
    description           text,
    rate_limit            integer,
    webhook_enabled       boolean                     not null,
    webhook_failure_count bigint                      not null,
    webhook_success_count bigint                      not null,
    last_webhook_failure  timestamp(6) with time zone,
    last_webhook_success  timestamp(6) with time zone,
    created_at            timestamp(6) with time zone not null,
    last_modified_at      timestamp(6) with time zone not null
);

create table users
(
    id                  uuid                        not null primary key,
    email               varchar(255)                not null unique,
    password_hash       varchar(255)                not null,
    first_name          varchar(100)                not null,
    last_name           varchar(100)                not null,
    role                varchar(20)                 not null check (role in ('USER', 'ADMIN')),
    status              varchar(20)                 not null check (status in ('ACTIVE', 'PENDING_VERIFICATION', 'SUSPENDED', 'DELETED')),
    phone_number        varchar(20),
    avatar_url          varchar(512),
    email_verified      boolean                     not null,
    faild_login_attemps integer                     not null,
    locked_until        timestamp(6) with time zone,
    last_login_at       timestamp(6) with time zone,
    referral_code       varchar(20) unique,
    referrer_id         uuid,
    created_at          timestamp(6) with time zone not null,
    last_modified_at    timestamp(6) with time zone not null
);
create index idx_user_status on users (status);
create index idx_user_referrer_id on users (referrer_id);

create table guests
(
    id               uuid                        not null primary key,
    name             varchar(200)                not null,
    email            varchar(255)                not null unique,
    phone            varchar(20),
    created_at       timestamp(6) with time zone not null,
    last_modified_at timestamp(6) with time zone not null
);

create table venues
(
    id                          uuid                        not null primary key,
    name                        varchar(255)                not null,
    address                     varchar(500)                not null,
    city                        varchar(100),
    description                 text,
    category                    varchar(50),
    status                      varchar(20)                 not null check (status in
                                                                            ('PENDING_APPROVAL', 'ACTIVE', 'SUSPENDED',
                                                                             'INACTIVE', 'DELETED')),
    phone_number                varchar(50),
    website                     varchar(500),
    image_url                   varchar(500),
    custom_domain               varchar(255),
    verification_document_url   varchar(500),
    official                    boolean                     not null,
    verified                    boolean                     not null,
    is_always_open              boolean                     not null,
    latitude                    double precision,
    longitude                   double precision,
    -- Payment & Integrations
    telcel_postpone_bill_issuer varchar(255),
    telcel_store_key            varchar(255),
    idram_rec_account           varchar(255),
    idram_secret_key            varchar(255),
    arca_username               varchar(255),
    arca_password               varchar(255),
    converse_merchant_id        varchar(255),
    converse_secret_key         varchar(255),
    smtp_email                  varchar(255),
    smtp_password               varchar(255),
    created_at                  timestamp(6) with time zone not null,
    last_modified_at            timestamp(6) with time zone not null
);
create index idx_venue_city on venues (city);
create index idx_venue_category on venues (category);
create index idx_venue_verified on venues (verified);
create index idx_venue_status on venues (status);

/* =========================================================
   2. Venue Dependent Tables
   ========================================================= */

create table staff
(
    id                            uuid                        not null primary key,
    venue_id                      uuid                        not null
        constraint fk_staff_venue references venues,
    email                         varchar(255)                not null unique,
    password_hash                 varchar(255)                not null,
    role                          varchar(20)                 not null check (role in ('OWNER', 'STAFF', 'EVENT_MANAGER')),
    email_verified                boolean                     not null,
    failed_login_attempts         integer                     not null,
    verification_token            varchar(255),
    verification_token_expires_at timestamp(6) with time zone,
    account_locked_until          timestamp(6) with time zone,
    last_login_at                 timestamp(6) with time zone,
    expires_at                    timestamp(6) with time zone,
    restricted_to_event_id        uuid,
    created_at                    timestamp(6) with time zone not null,
    last_modified_at              timestamp(6) with time zone not null
);
create index idx_staff_venue_id on staff (venue_id);

create table venue_followers
(
    id                    bigint generated by default as identity primary key,
    user_id               uuid                        not null,
    venue_id              uuid                        not null
        constraint fk_venue_followers_venue references venues,
    notifications_enabled boolean                     not null,
    created_at            timestamp(6) with time zone not null,
    last_modified_at      timestamp(6) with time zone not null,
    constraint uk_venue_follower_user_venue unique (venue_id, user_id)
);

create table venue_photos
(
    id               bigint generated by default as identity primary key,
    venue_id         uuid                        not null
        constraint fk_venue_photos_venue references venues,
    user_id          uuid                        not null,
    url              varchar(500)                not null,
    caption          varchar(500),
    display_order    integer                     not null,
    created_at       timestamp(6) with time zone not null,
    last_modified_at timestamp(6) with time zone not null
);

create table venue_promo_codes
(
    id                  uuid                        not null primary key,
    venue_id            uuid                        not null
        constraint fk_venue_promo_venue references venues,
    code                varchar(50)                 not null,
    description         varchar(255),
    discount_type       varchar(20)                 not null check (discount_type in ('PERCENTAGE', 'FIXED_AMOUNT')),
    discount_value      numeric(10, 2)              not null,
    min_order_amount    numeric(10, 2),
    max_discount_amount numeric(10, 2),
    is_active           boolean                     not null,
    max_usage_count     integer,
    current_usage_count integer                     not null,
    expires_at          timestamp(6) with time zone,
    created_at          timestamp(6) with time zone not null,
    last_modified_at    timestamp(6) with time zone not null,
    constraint uk_venue_promo_code_venue_code unique (venue_id, code)
);

create table venue_reviews
(
    id               bigint generated by default as identity primary key,
    venue_id         uuid                        not null
        constraint fk_venue_reviews_venue references venues,
    user_id          uuid                        not null,
    rating           integer                     not null,
    comment          text,
    is_moderated     boolean                     not null,
    created_at       timestamp(6) with time zone not null,
    last_modified_at timestamp(6) with time zone not null,
    constraint uk_venue_review_user_venue unique (venue_id, user_id)
);

create table venue_schedules
(
    id               bigint generated by default as identity primary key,
    venue_id         uuid                        not null
        constraint fk_venue_schedules_venue references venues,
    day_of_week      varchar(10)                 not null check (day_of_week in
                                                                 ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY',
                                                                  'FRIDAY', 'SATURDAY', 'SUNDAY')),
    open_time        time(6),
    close_time       time(6),
    is_closed        boolean                     not null,
    created_at       timestamp(6) with time zone not null,
    last_modified_at timestamp(6) with time zone not null,
    constraint uk_venue_schedule_venue_day unique (venue_id, day_of_week)
);

create table venue_translations
(
    id               bigint generated by default as identity primary key,
    venue_id         uuid                        not null
        constraint fk_venue_translations_venue references venues,
    language         varchar(10)                 not null,
    name             varchar(255)                not null,
    description      text,
    created_at       timestamp(6) with time zone not null,
    last_modified_at timestamp(6) with time zone not null,
    constraint uk_venue_translation_venue_language unique (venue_id, language)
);

create table seating_charts
(
    id                   uuid                        not null primary key,
    venue_id             uuid                        not null
        constraint fk_seating_charts_venue references venues,
    name                 varchar(255)                not null,
    background_url       varchar(500),
    level_indicator_size integer                     not null,
    seat_indicator_size  integer                     not null,
    created_at           timestamp(6) with time zone not null,
    last_modified_at     timestamp(6) with time zone not null
);
create index idx_seating_chart_venue_id on seating_charts (venue_id);
create index idx_seating_chart_name on seating_charts (name);

/* =========================================================
   3. Seating & Levels
   ========================================================= */

create table levels
(
    id               bigint generated by default as identity primary key,
    seating_chart_id uuid                        not null
        constraint fk_levels_seating_chart references seating_charts,
    parent_level_id  bigint
        constraint fk_levels_parent references levels,
    level_name       varchar(255)                not null,
    level_identifier varchar(50),
    capacity         integer,
    is_table         boolean                     not null,
    position_x       double precision,
    position_y       double precision,
    created_at       timestamp(6) with time zone not null,
    last_modified_at timestamp(6) with time zone not null
);
create index idx_level_seating_chart_id on levels (seating_chart_id);
create index idx_level_parent_id on levels (parent_level_id);

create table level_translations
(
    id               bigint generated by default as identity primary key,
    level_id         bigint                      not null
        constraint fk_level_translations_level references levels,
    language         varchar(10)                 not null,
    level_label      varchar(255)                not null,
    created_at       timestamp(6) with time zone not null,
    last_modified_at timestamp(6) with time zone not null,
    constraint uk_level_translation_level_language unique (level_id, language)
);

create table seats
(
    id               bigint generated by default as identity primary key,
    level_id         bigint                      not null
        constraint fk_seats_level references levels,
    seat_identifier  varchar(50)                 not null,
    seat_number      varchar(50),
    row_label        varchar(50),
    position_x       double precision,
    position_y       double precision,
    created_at       timestamp(6) with time zone not null,
    last_modified_at timestamp(6) with time zone not null,
    constraint uk_seat_level_identifier unique (level_id, seat_identifier)
);

/* =========================================================
   4. Events
   ========================================================= */

create table events
(
    id               uuid                        not null primary key,
    venue_id         uuid                        not null
        constraint fk_events_venue references venues,
    category_id      bigint
        constraint fk_events_category references event_categories,
    seating_chart_id uuid,
    title            varchar(255)                not null,
    description      text,
    status           varchar(20)                 not null check (status in
                                                                 ('UPCOMING', 'PAUSED', 'PAST', 'CANCELLED', 'DRAFT',
                                                                  'MAINTENANCE', 'ARCHIVED')),
    price_range      varchar(100),
    currency         varchar(3),
    img_url          varchar(500),
    location         varchar(500),
    latitude         double precision,
    longitude        double precision,
    created_at       timestamp(6) with time zone not null,
    last_modified_at timestamp(6) with time zone not null
);
create index idx_event_venue_id on events (venue_id);
create index idx_event_status on events (status);
create index idx_event_category_id on events (category_id);

create table event_category_translations
(
    id               bigint generated by default as identity primary key,
    category_id      bigint                      not null
        constraint fk_event_cat_trans_cat references event_categories,
    language         varchar(10)                 not null,
    name             varchar(100)                not null,
    created_at       timestamp(6) with time zone not null,
    last_modified_at timestamp(6) with time zone not null,
    constraint uk_category_translation_category_language unique (category_id, language)
);

create table event_price_templates
(
    id               uuid                        not null primary key,
    event_id         uuid                        not null
        constraint fk_price_templates_event references events,
    template_name    varchar(100)                not null,
    price            numeric(10, 2)              not null,
    color            varchar(7),
    created_at       timestamp(6) with time zone not null,
    last_modified_at timestamp(6) with time zone not null
);

create table event_secondary_images
(
    event_id  uuid not null
        constraint fk_secondary_images_event references events,
    image_url varchar(500)
);

create table event_tags
(
    event_id uuid not null
        constraint fk_event_tags_event references events,
    tag      varchar(50)
);

create table event_translations
(
    id               bigint generated by default as identity primary key,
    event_id         uuid                        not null
        constraint fk_event_translations_event references events,
    language         varchar(10)                 not null,
    title            varchar(255)                not null,
    description      text,
    created_at       timestamp(6) with time zone not null,
    last_modified_at timestamp(6) with time zone not null,
    constraint uk_event_translation_event_language unique (event_id, language)
);

create table event_sessions
(
    id                   uuid                        not null primary key,
    event_id             uuid                        not null
        constraint fk_sessions_event references events,
    status               varchar(20)                 not null check (status in
                                                                     ('UPCOMING', 'PAUSED', 'PAST', 'CANCELLED',
                                                                      'DRAFT', 'MAINTENANCE', 'ARCHIVED')),
    start_time           timestamp(6) with time zone not null,
    end_time             timestamp(6) with time zone not null,
    tickets_count        integer,
    tickets_sold         integer                     not null,
    price_override       numeric(10, 2),
    price_range_override varchar(100),
    created_at           timestamp(6) with time zone not null,
    last_modified_at     timestamp(6) with time zone not null
);

create table event_session_price_overrides
(
    id               bigint generated by default as identity primary key,
    session_id       uuid                        not null
        constraint fk_session_price_overrides_session references event_sessions,
    template_name    varchar(100)                not null,
    price            numeric(10, 2)              not null,
    created_at       timestamp(6) with time zone not null,
    last_modified_at timestamp(6) with time zone not null
);

/* =========================================================
   5. Session Configuration
   ========================================================= */

create table session_level_configs
(
    id                bigint generated by default as identity primary key,
    session_id        uuid                        not null
        constraint fk_session_level_configs_session references event_sessions,
    level_id          bigint                      not null,
    price_template_id uuid
        constraint fk_session_level_configs_price references event_price_templates,
    status            varchar(20)                 not null check (status in ('AVAILABLE', 'RESERVED', 'SOLD', 'CLOSED', 'BLOCKED')),
    capacity          integer,
    sold_count        integer                     not null,
    created_at        timestamp(6) with time zone not null,
    last_modified_at  timestamp(6) with time zone not null,
    constraint uk_session_level_config unique (session_id, level_id)
);

create table session_seat_configs
(
    id                bigint generated by default as identity primary key,
    session_id        uuid                        not null
        constraint fk_session_seat_configs_session references event_sessions,
    seat_id           bigint                      not null,
    price_template_id uuid
        constraint fk_session_seat_configs_price references event_price_templates,
    status            varchar(20)                 not null check (status in ('AVAILABLE', 'RESERVED', 'SOLD', 'CLOSED', 'BLOCKED')),
    created_at        timestamp(6) with time zone not null,
    last_modified_at  timestamp(6) with time zone not null,
    constraint uk_session_seat_config unique (session_id, seat_id)
);

create table session_table_configs
(
    id                bigint generated by default as identity primary key,
    session_id        uuid                        not null
        constraint fk_session_table_configs_session references event_sessions,
    table_id          bigint                      not null,
    price_template_id uuid
        constraint fk_session_table_configs_price references event_price_templates,
    booking_mode      varchar(20)                 not null check (booking_mode in ('SEATS_ONLY', 'TABLE_ONLY', 'FLEXIBLE')),
    status            varchar(20)                 not null check (status in ('AVAILABLE', 'RESERVED', 'SOLD', 'CLOSED', 'BLOCKED')),
    created_at        timestamp(6) with time zone not null,
    last_modified_at  timestamp(6) with time zone not null,
    constraint uk_session_table_config unique (session_id, table_id)
);

/* =========================================================
   6. User Related Tables
   ========================================================= */

create table user_blocked_users
(
    id               bigint generated by default as identity primary key,
    blocking_user_id uuid                        not null
        constraint fk_user_blocked_blocker references users,
    blocked_user_id  uuid                        not null
        constraint fk_user_blocked_blocked references users,
    block_reason     varchar(50),
    created_at       timestamp(6) with time zone not null,
    last_modified_at timestamp(6) with time zone not null,
    constraint uk_blocking_blocked_user unique (blocking_user_id, blocked_user_id)
);

create table user_favorite_events
(
    id                    bigint generated by default as identity primary key,
    user_id               uuid                        not null
        constraint fk_user_fav_user references users,
    event_id              uuid                        not null,
    notifications_enabled boolean                     not null,
    created_at            timestamp(6) with time zone not null,
    last_modified_at      timestamp(6) with time zone not null,
    constraint uk_user_event_favorite unique (user_id, event_id)
);

create table user_fcm_tokens
(
    id               bigint generated by default as identity primary key,
    user_id          uuid                        not null
        constraint fk_user_fcm_user references users,
    token            varchar(512)                not null unique,
    platform         varchar(20)                 not null,
    device_name      varchar(100),
    last_used_at     timestamp(6) with time zone,
    created_at       timestamp(6) with time zone not null,
    last_modified_at timestamp(6) with time zone not null
);
create index idx_fcm_user_id on user_fcm_tokens (user_id);

create table user_promo_codes
(
    id                 bigint generated by default as identity primary key,
    user_id            uuid                        not null
        constraint fk_user_promo_user references users,
    promo_code         varchar(50)                 not null,
    discount_type      varchar(20)                 not null check (discount_type in ('PERCENTAGE', 'FIXED_AMOUNT')),
    discount_value     numeric(10, 2)              not null,
    status             varchar(20)                 not null check (status in ('AVAILABLE', 'USED', 'EXHAUSTED', 'EXPIRED', 'REVOKED')),
    max_uses           integer,
    times_used         integer                     not null,
    used_in_booking_id uuid,
    expires_at         timestamp(6) with time zone,
    created_at         timestamp(6) with time zone not null,
    last_modified_at   timestamp(6) with time zone not null,
    constraint uk_user_promo_code unique (user_id, promo_code)
);

/* =========================================================
   7. Bookings & Carts
   ========================================================= */

create table bookings
(
    id                    uuid                        not null primary key,
    reservation_token     uuid                        not null unique,
    session_id            uuid                        not null,
    venue_id              uuid,
    user_id               uuid,
    guest_id              uuid
        constraint fk_bookings_guest references guests,
    platform_id           uuid,
    payment_id            uuid,
    status                varchar(20)                 not null check (status in ('PENDING', 'CONFIRMED', 'CANCELLED', 'REFUNDED')),
    total_price           numeric(10, 2)              not null,
    currency              varchar(3)                  not null,
    external_order_number varchar(100) unique,
    cancellation_reason   varchar(500),
    cancelled_at          timestamp(6) with time zone,
    confirmed_at          timestamp(6) with time zone,
    created_at            timestamp(6) with time zone not null,
    last_modified_at      timestamp(6) with time zone not null
);
create index idx_booking_user_id on bookings (user_id);
create index idx_booking_guest_id on bookings (guest_id);
create index idx_booking_session_id on bookings (session_id);
create index idx_booking_platform_id on bookings (platform_id);
create index idx_booking_venue_id on bookings (venue_id);
create index idx_booking_reservation_token on bookings (reservation_token);


create table booking_items
(
    id                  bigint generated by default as identity primary key,
    booking_id          uuid                        not null
        constraint fk_booking_items_booking references bookings,
    quantity            integer                     not null,
    unit_price          numeric(10, 2)              not null,
    seat_id             bigint,
    level_id            bigint,
    price_template_name varchar(100),
    created_at          timestamp(6) with time zone not null,
    last_modified_at    timestamp(6) with time zone not null
);

create table carts
(
    id               uuid                        not null primary key,
    token            uuid                        not null unique,
    user_id          uuid,
    event_session_id uuid                        not null,
    expires_at       timestamp(6) with time zone not null,
    last_activity_at timestamp(6) with time zone not null,
    created_at       timestamp(6) with time zone not null,
    last_modified_at timestamp(6) with time zone not null
);
create index idx_cart_token on carts (token);
create index idx_cart_user_id on carts (user_id);
create index idx_cart_expires_at on carts (expires_at);

create table cart_item
(
    id               bigint generated by default as identity primary key,
    cart_id          uuid                        not null
        constraint fk_cart_item_cart references carts,
    session_id       uuid                        not null,
    level_id         bigint                      not null,
    quantity         integer                     not null,
    unit_price       numeric(10, 2)              not null,
    created_at       timestamp(6) with time zone not null,
    last_modified_at timestamp(6) with time zone not null
);

create table cart_seats
(
    id               bigint generated by default as identity primary key,
    cart_id          uuid                        not null
        constraint fk_cart_seats_cart references carts,
    session_id       uuid                        not null,
    seat_id          bigint                      not null,
    unit_price       numeric(10, 2)              not null,
    created_at       timestamp(6) with time zone not null,
    last_modified_at timestamp(6) with time zone not null,
    constraint uk_cart_seat_session_seat unique (session_id, seat_id)
);

create table cart_tables
(
    id               bigint generated by default as identity primary key,
    cart_id          uuid                        not null
        constraint fk_cart_tables_cart references carts,
    session_id       uuid                        not null,
    table_id         bigint                      not null,
    unit_price       numeric(10, 2)              not null,
    created_at       timestamp(6) with time zone not null,
    last_modified_at timestamp(6) with time zone not null,
    constraint uk_cart_table_session_table unique (session_id, table_id)
);

/* =========================================================
   8. Webhooks
   ========================================================= */

create table webhook_events
(
    id               uuid                        not null primary key,
    platform_id      uuid                        not null,
    session_id       uuid                        not null,
    event_type       varchar(50)                 not null check (event_type in
                                                                 ('SEAT_RESERVED', 'SEAT_RELEASED', 'SEAT_BOOKED',
                                                                  'BOOKING_CANCELLED', 'GA_AVAILABILITY_CHANGED',
                                                                  'SESSION_CONFIG_UPDATED')),
    status           varchar(20)                 not null check (status in ('PENDING', 'DELIVERED', 'FAILED')),
    payload          text                        not null,
    response_code    integer,
    response_body    text,
    error_message    text,
    attempt_count    integer                     not null,
    last_attempt_at  timestamp(6) with time zone,
    next_retry_at    timestamp(6) with time zone,
    seat_identifier  varchar(50),
    level_identifier varchar(50),
    created_at       timestamp(6) with time zone not null,
    last_modified_at timestamp(6) with time zone not null
);
create index idx_webhook_platform_id on webhook_events (platform_id);
create index idx_webhook_status on webhook_events (status);
create index idx_webhook_next_retry on webhook_events (next_retry_at);