/* =========================================================
   1. Reference Data & Independent Tables
   ========================================================= */

-- Location hierarchy
create table ref_regions
(
    id               bigint generated by default as identity primary key,
    code             varchar(10)                 not null unique,
    names            jsonb                       not null,
    display_order    integer,
    is_active        boolean                     not null default true,
    created_at       timestamp(6) with time zone not null,
    last_modified_at timestamp(6) with time zone not null
);
create index idx_region_code on ref_regions (code);

create table ref_cities
(
    id               bigint generated by default as identity primary key,
    region_id        bigint                      not null
        constraint fk_city_region references ref_regions (id),
    slug             varchar(100)                not null unique,
    names            jsonb                       not null,
    official_id      varchar(50),
    display_order    integer,
    is_active        boolean                     not null default true,
    created_at       timestamp(6) with time zone not null,
    last_modified_at timestamp(6) with time zone not null
);
create index idx_city_slug on ref_cities (slug);
create index idx_city_region on ref_cities (region_id);
create index idx_city_active on ref_cities (is_active);

-- Venue categories reference table
create table ref_venue_categories
(
    id               bigint generated by default as identity primary key,
    code             varchar(50)                 not null unique,
    names            jsonb                       not null,
    icon             varchar(50),
    color            varchar(7),
    display_order    integer                     not null default 0,
    is_active        boolean                     not null default true,
    created_at       timestamp(6) with time zone not null,
    last_modified_at timestamp(6) with time zone not null
);

create table ref_event_categories
(
    id               bigint generated by default as identity primary key,
    code          varchar(50) not null unique,
    names         jsonb       not null,
    icon          varchar(50),
    color            varchar(7),
    display_order integer     not null default 0,
    is_active     boolean     not null default true,
    created_at       timestamp(6) with time zone not null,
    last_modified_at timestamp(6) with time zone not null
);

create table platforms
(
    id                    uuid                        not null primary key,
    name                  varchar(100)                not null unique,
    status                varchar(20)                 not null check (status in ('ACTIVE', 'SUSPENDED', 'INACTIVE')),
    api_url               varchar(500)                not null,
    shared_secret         varchar(255)                not null,
    contact_email         varchar(255),
    description           text,
    rate_limit            integer,
    webhook_enabled       boolean                     not null,
    webhook_failure_count bigint                      not null,
    webhook_success_count bigint                      not null,
    last_webhook_failure  timestamp(6) with time zone,
    last_webhook_success  timestamp(6) with time zone,
    created_at            timestamp(6) with time zone not null,
    last_modified_at      timestamp(6) with time zone not null
);

create table users
(
    id                    uuid                        not null primary key,
    email                 varchar(255)                not null unique,
    password_hash         varchar(255)                not null,
    first_name            varchar(100)                not null,
    last_name             varchar(100)                not null,
    status  varchar(20) not null check (status in ('PENDING_VERIFICATION', 'ACTIVE', 'SUSPENDED', 'DELETED')),
    phone_number          varchar(20),
    avatar_url            varchar(512),
    email_verified        boolean                     not null,
    failed_login_attempts integer                     not null,
    version bigint      not null default 0,
    locked_until          timestamp(6) with time zone,
    last_login_at         timestamp(6) with time zone,
    referral_code         varchar(20) unique,
    referrer_id           uuid,
    created_at            timestamp(6) with time zone not null,
    last_modified_at      timestamp(6) with time zone not null
);
create index idx_user_email on users (email);
create index idx_user_status on users (status);
create index idx_user_referrer_id on users (referrer_id);

create table guests
(
    id               uuid                        not null primary key,
    name             varchar(200)                not null,
    email            varchar(255)                not null unique,
    phone            varchar(20),
    created_at       timestamp(6) with time zone not null,
    last_modified_at timestamp(6) with time zone not null
);
create index idx_guest_email on guests (email);

-- Organizations (Legal entities / Tenants)
create table organizations
(
    id                          uuid                        not null primary key,
    name                        varchar(255)                not null,
    slug                        varchar(100)                not null unique,
    type                        varchar(20)                 not null check (type in ('GOVERNMENT', 'MUNICIPAL', 'CULTURAL', 'PRIVATE', 'NON_PROFIT')),
    legal_name                  varchar(255),
    tax_id                      varchar(50),
    contact_email               varchar(255),
    phone_number                varchar(20),
    website_url                 varchar(500),
    custom_domain               varchar(255) unique,
    branding_config             jsonb,
    default_merchant_profile_id uuid,
    is_active                   boolean                     not null default true,
    created_at                  timestamp(6) with time zone not null,
    last_modified_at            timestamp(6) with time zone not null
);
create index idx_org_slug on organizations (slug);
create index idx_org_domain on organizations (custom_domain);
create index idx_org_status on organizations (is_active);

-- Merchant Profiles (Financial destinations)
create table merchant_profile
(
    id               uuid                        not null primary key,
    name             varchar(255)                not null,
    legal_name       varchar(255),
    tax_id           varchar(255),
    organization_id  uuid                        not null,
    config_json      text,
    created_at       timestamp(6) with time zone not null,
    last_modified_at timestamp(6) with time zone not null
);

/* =========================================================
   2. Venues & Structure
   ========================================================= */

-- The Main Venue Entity
create table venues
(
    id                  uuid                        not null primary key,
    organization_id     uuid                        not null, -- Parent Organization
    city_id             bigint                      not null
        constraint fk_venue_city references ref_cities (id),
    merchant_profile_id uuid,
    category_id         bigint
        constraint fk_venue_category references ref_venue_categories (id),

    -- Content
    name                varchar(255)                not null,
    slug                varchar(255)                not null unique,
    description         text,
    address             varchar(500)                not null,

    -- Legal & Config
    legal_name          varchar(255),
    tax_id              varchar(50),
    time_zone           varchar(50)                 not null default 'Asia/Yerevan',
    latitude            double precision,
    longitude           double precision,
    is_always_open      boolean                     not null default false,
    custom_domain       varchar(255),
    ownership_type      varchar(20) check (ownership_type in ('STATE_OWNED', 'MUNICIPAL', 'PRIVATE', 'NGO', 'OTHER')),
    status              varchar(20)                 not null default 'PENDING_APPROVAL'
        check (status in ('PENDING_APPROVAL', 'ACTIVE', 'SUSPENDED', 'INACTIVE', 'DELETED')),

    -- Contact & Visuals
    phone_number        varchar(50),
    website             varchar(500),
    contact_email       varchar(255),
    logo_url            varchar(500),
    cover_image_url     varchar(500),
    social_links        jsonb,
    notification_emails jsonb                       not null default '[]'::jsonb,

    created_at          timestamp(6) with time zone not null,
    last_modified_at    timestamp(6) with time zone not null
);
create index idx_venue_city on venues (city_id);
create index idx_venue_slug on venues (slug);
create index idx_venue_status on venues (status);

-- Organization-Venue Link (Junction Table)
create table organization_venue_links
(
    id               bigint generated by default as identity primary key,
    organization_id  uuid                        not null
        constraint fk_org_venue_link_org references organizations (id),
    venue_id         uuid                        not null
        constraint fk_org_venue_link_venue references venues (id),
    is_active        boolean                     not null default true,
    created_at       timestamp(6) with time zone not null,
    last_modified_at timestamp(6) with time zone not null
);
create index idx_org_venue_link_org on organization_venue_links (organization_id);
create index idx_org_venue_link_venue on organization_venue_links (venue_id);
create index idx_org_venue_link_active on organization_venue_links (is_active);

-- Venue Sensitive Settings (Vertical Partitioning)
create table venue_settings
(
    venue_id           uuid                        not null primary key
        constraint fk_venue_settings_venue references venues (id) on delete cascade,
    smtp_config_json   text,
    custom_config_json text,
    created_at         timestamp(6) with time zone not null default now(),
    last_modified_at   timestamp(6) with time zone not null default now()
);

create table venue_branding
(
    venue_id        uuid not null primary key
        constraint fk_venue_branding_venue references venues (id) on delete cascade,
    primary_color   varchar(7),
    secondary_color varchar(7),
    favicon_url     varchar(500),
    home_hero       jsonb,
    about_blocks    jsonb,
    contact_config  jsonb
);

/* =========================================================
   3. Staff & Security
   ========================================================= */

create table staff_identities
(
    id                            uuid                        not null primary key,
    email                         varchar(255)                not null unique,
    password_hash                 varchar(255)                not null,
    first_name              varchar(100),
    last_name               varchar(100),
    is_platform_super_admin boolean     not null default false,
    status                  varchar(20) not null default 'PENDING_VERIFICATION'
        check (status in ('PENDING_VERIFICATION', 'ACTIVE', 'SUSPENDED', 'LOCKED', 'DELETED')),
    failed_login_attempts   integer     not null default 0,
    version                 bigint      not null default 0,
    account_locked_until    timestamp(6) with time zone,
    last_login_at           timestamp(6) with time zone,
    verification_token            varchar(255),
    verification_token_expires_at timestamp(6) with time zone,
    created_at                    timestamp(6) with time zone not null,
    last_modified_at              timestamp(6) with time zone not null
);
create index idx_staff_email on staff_identities (email);
create index idx_staff_status on staff_identities (status);

create table staff_memberships
(
    id                uuid                        not null primary key,
    staff_identity_id uuid                        not null
        constraint fk_membership_staff references staff_identities (id),
    organization_id   uuid                        not null,
    org_role          varchar(20)                 not null default 'MEMBER'
        check (org_role in ('MEMBER', 'ADMIN', 'OWNER')),
    is_active         boolean                     not null default true,
    created_at        timestamp(6) with time zone not null,
    last_modified_at  timestamp(6) with time zone not null,
    constraint uk_staff_org_membership unique (staff_identity_id, organization_id)
);

create table staff_venue_permissions
(
    id               uuid                        not null primary key,
    membership_id    uuid                        not null
        constraint fk_venue_perm_membership references staff_memberships (id),
    venue_id         uuid                        not null,
    role             varchar(20)                 not null
        check (role in ('VIEWER', 'SCANNER', 'EDITOR', 'MANAGER')),
    created_at       timestamp(6) with time zone not null,
    last_modified_at timestamp(6) with time zone not null,
    constraint uk_membership_venue_permission unique (membership_id, venue_id)
);

/* =========================================================
   4. Venue dependent sub-tables
   ========================================================= */

create table venue_followers
(
    id                    bigint generated by default as identity primary key,
    user_id               uuid                        not null,
    venue_id              uuid                        not null
        constraint fk_venue_followers_venue references venues (id),
    notifications_enabled boolean                     not null,
    created_at            timestamp(6) with time zone not null,
    last_modified_at      timestamp(6) with time zone not null,
    constraint uk_venue_follower_user_venue unique (venue_id, user_id)
);

create table venue_photos
(
    id               bigint generated by default as identity primary key,
    venue_id         uuid                        not null
        constraint fk_venue_photos_venue references venues (id),
    user_id          uuid                        not null,
    url              varchar(500)                not null,
    caption          varchar(500),
    display_order    integer                     not null,
    created_at       timestamp(6) with time zone not null,
    last_modified_at timestamp(6) with time zone not null
);

create table venue_promo_codes
(
    id                  uuid                        not null primary key,
    venue_id            uuid                        not null
        constraint fk_venue_promo_venue references venues (id),
    code                varchar(50)                 not null,
    description         varchar(255),
    discount_type       varchar(20)                 not null check (discount_type in ('PERCENTAGE', 'FIXED_AMOUNT')),
    discount_value      numeric(10, 2)              not null,
    min_order_amount    numeric(10, 2),
    max_discount_amount numeric(10, 2),
    is_active           boolean                     not null,
    max_usage_count     integer,
    current_usage_count integer                     not null,
    expires_at          timestamp(6) with time zone,
    created_at          timestamp(6) with time zone not null,
    last_modified_at    timestamp(6) with time zone not null,
    constraint uk_venue_promo_code_venue_code unique (venue_id, code)
);

create table venue_reviews
(
    id               bigint generated by default as identity primary key,
    venue_id         uuid                        not null
        constraint fk_venue_reviews_venue references venues (id),
    user_id          uuid                        not null,
    rating           integer                     not null,
    comment          text,
    is_moderated     boolean                     not null,
    created_at       timestamp(6) with time zone not null,
    last_modified_at timestamp(6) with time zone not null,
    constraint uk_venue_review_user_venue unique (venue_id, user_id)
);

create table venue_schedules
(
    id               bigint generated by default as identity primary key,
    venue_id         uuid                        not null
        constraint fk_venue_schedules_venue references venues (id),
    day_of_week      varchar(10)                 not null check (day_of_week in
                                                                 ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY',
                                                                  'FRIDAY', 'SATURDAY', 'SUNDAY')),
    open_time        time(6),
    close_time       time(6),
    is_closed        boolean                     not null,
    created_at       timestamp(6) with time zone not null,
    last_modified_at timestamp(6) with time zone not null,
    constraint uk_venue_schedule_venue_day unique (venue_id, day_of_week)
);

create table venue_translations
(
    id               bigint generated by default as identity primary key,
    venue_id         uuid                        not null
        constraint fk_venue_translations_venue references venues (id),
    language         varchar(10)                 not null,
    name             varchar(255)                not null,
    description      text,
    address          varchar(500),
    created_at       timestamp(6) with time zone not null,
    last_modified_at timestamp(6) with time zone not null,
    constraint uk_venue_translation_venue_language unique (venue_id, language)
);

/* =========================================================
   5. Seating Chart Architecture
   ========================================================= */

create table seating_charts
(
    id                uuid                        not null primary key,
    venue_id          uuid                        not null
        constraint fk_seating_charts_venue references venues (id),
    name              varchar(255)                not null,
    width             integer                     not null default 2000,
    height            integer                     not null default 2000,
    is_active         boolean                     not null default true,
    background_url    varchar(500),
    style_config_json text,
    created_at        timestamp(6) with time zone not null,
    last_modified_at  timestamp(6) with time zone not null
);
create index idx_chart_venue on seating_charts (venue_id);
create index idx_chart_active on seating_charts (is_active);

create table chart_zones
(
    id               bigint generated by default as identity primary key,
    chart_id         uuid                        not null
        constraint fk_zones_chart references seating_charts (id),
    parent_zone_id   bigint
        constraint fk_zones_parent references chart_zones (id),
    name             varchar(100)                not null,
    code             varchar(50)                 not null,
    x_position       double precision            not null,
    y_position       double precision            not null,
    rotation         double precision            not null default 0.0,
    boundary_path    text,
    display_color    varchar(7),
    created_at       timestamp(6) with time zone not null,
    last_modified_at timestamp(6) with time zone not null,
    constraint uk_zone_chart_code unique (chart_id, code)
);
create index idx_zone_chart_id on chart_zones (chart_id);

create table chart_tables
(
    id               bigint generated by default as identity primary key,
    zone_id          bigint                      not null
        constraint fk_tables_zone references chart_zones (id),
    table_number     varchar(20)                 not null,
    code             varchar(150)                not null,
    seat_capacity    integer                     not null default 4,
    shape            varchar(20)                 not null check (shape in ('ROUND', 'SQUARE', 'RECTANGLE', 'OVAL')),
    x_position       double precision            not null,
    y_position       double precision            not null,
    width            double precision            not null,
    height           double precision            not null,
    rotation         double precision            not null default 0.0,
    created_at       timestamp(6) with time zone not null,
    last_modified_at timestamp(6) with time zone not null,
    constraint uk_table_zone_code unique (zone_id, code)
);

create table chart_seats
(
    id                 bigint generated by default as identity primary key,
    zone_id            bigint                      not null
        constraint fk_seats_zone references chart_zones (id),
    table_id           bigint
        constraint fk_seats_table references chart_tables (id),
    row_label          varchar(20)                 not null,
    seat_number        varchar(20)                 not null,
    code               varchar(150)                not null,
    category_key       varchar(50)                 not null default 'STANDARD',
    is_accessible      boolean                     not null default false,
    is_obstructed_view boolean                     not null default false,
    x_position         double precision            not null,
    y_position         double precision            not null,
    rotation           double precision            not null default 0.0,
    created_at         timestamp(6) with time zone not null,
    last_modified_at   timestamp(6) with time zone not null,
    constraint uk_seat_zone_code unique (zone_id, code)
);
create index idx_seat_code on chart_seats (code);

create table chart_ga_areas
(
    id               bigint generated by default as identity primary key,
    zone_id       bigint       not null
        constraint fk_ga_areas_zone references chart_zones (id),
    name          varchar(100) not null,
    code          varchar(150) not null,
    capacity      integer      not null,
    boundary_path text,
    display_color varchar(7),
    created_at       timestamp(6) with time zone not null,
    last_modified_at timestamp(6) with time zone not null,
    constraint uk_ga_zone_code unique (zone_id, code)
);
create index idx_ga_code on chart_ga_areas (code);

/* =========================================================
   6. Events & Inventory
   ========================================================= */

create table events
(
    id                  uuid                        not null primary key,
    venue_id            uuid                        not null
        constraint fk_events_venue references venues (id),
    category_id         bigint
        constraint fk_events_category references ref_event_categories (id),
    seating_chart_id    uuid
        constraint fk_events_seating_chart references seating_charts (id),
    merchant_profile_id uuid,
    title               varchar(255)                not null,
    description         text,
    status              varchar(20)                 not null default 'DRAFT'
        check (status in ('UPCOMING', 'PAUSED', 'PAST', 'CANCELLED', 'DRAFT', 'MAINTENANCE', 'ARCHIVED')),
    price_range         varchar(100),
    currency            varchar(3)                           default 'AMD',
    img_url             varchar(500),
    location            varchar(500),
    latitude            double precision,
    longitude           double precision,
    created_at          timestamp(6) with time zone not null,
    last_modified_at    timestamp(6) with time zone not null
);
create index idx_event_venue_id on events (venue_id);
create index idx_event_status on events (status);
create index idx_event_category_id on events (category_id);

create table event_price_templates
(
    id               uuid                        not null primary key,
    event_id         uuid                        not null
        constraint fk_price_templates_event references events (id),
    template_name    varchar(100)                not null,
    price            numeric(10, 2)              not null,
    color            varchar(7),
    is_anchor boolean not null default false,
    created_at       timestamp(6) with time zone not null,
    last_modified_at timestamp(6) with time zone not null
);

create table event_secondary_images
(
    event_id  uuid not null
        constraint fk_secondary_images_event references events (id),
    image_url varchar(500)
);

create table event_tags
(
    event_id uuid not null
        constraint fk_event_tags_event references events (id),
    tag      varchar(50)
);

create table event_translations
(
    id               bigint generated by default as identity primary key,
    event_id         uuid                        not null
        constraint fk_event_translations_event references events (id),
    language         varchar(10)                 not null,
    title            varchar(255)                not null,
    description      text,
    created_at       timestamp(6) with time zone not null,
    last_modified_at timestamp(6) with time zone not null,
    constraint uk_event_translation_event_language unique (event_id, language)
);

create table event_sessions
(
    id                   uuid                        not null primary key,
    event_id             uuid                        not null
        constraint fk_sessions_event references events (id),
    status               varchar(20)                 not null check (status in
                                                                     ('UPCOMING', 'PAUSED', 'PAST', 'CANCELLED',
                                                                      'DRAFT', 'MAINTENANCE', 'ARCHIVED')),
    start_time           timestamp(6) with time zone not null,
    end_time             timestamp(6) with time zone not null,
    tickets_count        integer,
    tickets_sold         integer                     not null,
    price_override       numeric(10, 2),
    price_range_override varchar(100),
    created_at           timestamp(6) with time zone not null,
    last_modified_at     timestamp(6) with time zone not null
);

create table event_session_price_overrides
(
    id               bigint generated by default as identity primary key,
    session_id       uuid                        not null
        constraint fk_session_price_overrides_session references event_sessions (id),
    template_name    varchar(100)                not null,
    price            numeric(10, 2)              not null,
    created_at       timestamp(6) with time zone not null,
    last_modified_at timestamp(6) with time zone not null
);

/* =========================================================
   7. Session Configuration (Availability)
   ========================================================= */

create table session_level_configs
(
    id                bigint generated by default as identity primary key,
    session_id        uuid                        not null
        constraint fk_session_level_configs_session references event_sessions (id),
    ga_area_id        bigint                      not null
        constraint fk_session_level_configs_area references chart_ga_areas (id),
    price_template_id uuid
        constraint fk_session_level_configs_price references event_price_templates (id),
    status            varchar(20)                 not null check (status in
                                                                  ('AVAILABLE', 'RESERVED', 'SOLD', 'CLOSED',
                                                                   'BLOCKED')),
    capacity          integer,
    sold_count        integer                     not null default 0,
    created_at        timestamp(6) with time zone not null,
    last_modified_at  timestamp(6) with time zone not null,
    constraint uk_session_level_config unique (session_id, ga_area_id)
);

create table session_seat_configs
(
    id                bigint generated by default as identity primary key,
    session_id        uuid                        not null
        constraint fk_session_seat_configs_session references event_sessions (id),
    seat_id           bigint                      not null
        constraint fk_session_seat_configs_seat references chart_seats (id),
    price_template_id uuid
        constraint fk_session_seat_configs_price references event_price_templates (id),
    status            varchar(20)                 not null check (status in
                                                                  ('AVAILABLE', 'RESERVED', 'SOLD', 'CLOSED',
                                                                   'BLOCKED')),
    created_at        timestamp(6) with time zone not null,
    last_modified_at  timestamp(6) with time zone not null,
    constraint uk_session_seat_config unique (session_id, seat_id)
);
create index idx_session_seat_status on session_seat_configs (session_id, status);

create table session_table_configs
(
    id                bigint generated by default as identity primary key,
    session_id        uuid                        not null
        constraint fk_session_table_configs_session references event_sessions (id),
    table_id          bigint                      not null
        constraint fk_session_table_configs_table references chart_tables (id),
    price_template_id uuid
        constraint fk_session_table_configs_price references event_price_templates (id),
    booking_mode      varchar(20)                 not null check (booking_mode in
                                                                  ('SEATS_ONLY', 'TABLE_ONLY', 'FLEXIBLE')),
    status            varchar(20)                 not null check (status in
                                                                  ('AVAILABLE', 'RESERVED', 'SOLD', 'CLOSED',
                                                                   'BLOCKED')),
    created_at        timestamp(6) with time zone not null,
    last_modified_at  timestamp(6) with time zone not null,
    constraint uk_session_table_config unique (session_id, table_id)
);

/* =========================================================
   8. User Related Tables
   ========================================================= */

create table user_blocked_users
(
    id               bigint generated by default as identity primary key,
    blocking_user_id uuid                        not null
        constraint fk_user_blocked_blocker references users (id),
    blocked_user_id  uuid                        not null
        constraint fk_user_blocked_blocked references users (id),
    block_reason     varchar(50),
    created_at       timestamp(6) with time zone not null,
    last_modified_at timestamp(6) with time zone not null,
    constraint uk_blocking_blocked_user unique (blocking_user_id, blocked_user_id)
);

create table user_favorite_events
(
    id                    bigint generated by default as identity primary key,
    user_id               uuid                        not null
        constraint fk_user_fav_user references users (id),
    event_id              uuid                        not null,
    notifications_enabled boolean                     not null,
    created_at            timestamp(6) with time zone not null,
    last_modified_at      timestamp(6) with time zone not null,
    constraint uk_user_event_favorite unique (user_id, event_id)
);

create table user_fcm_tokens
(
    id               bigint generated by default as identity primary key,
    user_id          uuid                        not null
        constraint fk_user_fcm_user references users (id),
    token            varchar(512)                not null unique,
    platform         varchar(20)                 not null,
    device_name      varchar(100),
    last_used_at     timestamp(6) with time zone,
    created_at       timestamp(6) with time zone not null,
    last_modified_at timestamp(6) with time zone not null
);
create index idx_fcm_user_id on user_fcm_tokens (user_id);

-- Note: UserPromoCode Kotlin entity was not provided, but keeping strictly for table existence
create table user_promo_codes
(
    id                 bigint generated by default as identity primary key,
    user_id            uuid                        not null
        constraint fk_user_promo_user references users (id),
    promo_code         varchar(50)                 not null,
    discount_type      varchar(20)                 not null check (discount_type in ('PERCENTAGE', 'FIXED_AMOUNT')),
    discount_value     numeric(10, 2)              not null,
    status             varchar(20)                 not null check (status in ('AVAILABLE', 'USED', 'EXHAUSTED', 'EXPIRED', 'REVOKED')),
    max_uses           integer,
    times_used         integer                     not null,
    used_in_booking_id uuid,
    expires_at         timestamp(6) with time zone,
    created_at         timestamp(6) with time zone not null,
    last_modified_at   timestamp(6) with time zone not null,
    constraint uk_user_promo_code unique (user_id, promo_code)
);

/* =========================================================
   9. Bookings & Carts
   ========================================================= */

create table bookings
(
    id                    uuid                        not null primary key,
    user_id               uuid,
    guest_id              uuid
        constraint fk_bookings_guest references guests (id),
    session_id            uuid        not null,
    total_price           numeric(10, 2)              not null,
    currency              varchar(3)                  not null,
    platform_id           uuid,
    venue_id              uuid,
    external_order_number varchar(100) unique,
    status                varchar(20) not null check (status in
                                                      ('PENDING', 'CONFIRMED', 'CANCELLED', 'REFUNDED')),
    confirmed_at          timestamp(6) with time zone,
    cancelled_at          timestamp(6) with time zone,
    cancellation_reason   varchar(500),
    payment_id            uuid,

    -- Added to match Booking.kt
    service_fee_amount numeric(10, 2) not null default 0,
    discount_amount    numeric(10, 2) not null default 0,
    promo_code         varchar(50),
    version            bigint         not null default 0,

    created_at            timestamp(6) with time zone not null,
    last_modified_at      timestamp(6) with time zone not null
);
create index idx_booking_user_id on bookings (user_id);
create index idx_booking_guest_id on bookings (guest_id);
create index idx_booking_session_id on bookings (session_id);
create index idx_booking_platform_id on bookings (platform_id);
create index idx_booking_venue_id on bookings (venue_id);

create table booking_items
(
    id                  bigint generated by default as identity primary key,
    booking_id          uuid                        not null
        constraint fk_booking_items_booking references bookings (id),
    quantity            integer                     not null,
    unit_price          numeric(10, 2)              not null,
    seat_id             bigint
        constraint fk_booking_items_seat references chart_seats (id),
    ga_area_id          bigint
        constraint fk_booking_items_ga_area references chart_ga_areas (id),
    -- Added to match BookingItem.kt
    table_id bigint
        constraint fk_booking_items_table references chart_tables (id),

    price_template_name varchar(100),
    created_at          timestamp(6) with time zone not null,
    last_modified_at    timestamp(6) with time zone not null
);

create table carts
(
    id               uuid                        not null primary key,
    event_session_id uuid                        not null,
    expires_at       timestamp(6) with time zone not null,
    token   uuid not null unique,
    user_id uuid,

    -- Added to match Cart.kt
    promo_code      varchar(50),
    discount_amount numeric(10, 2),

    last_activity_at timestamp(6) with time zone not null,
    created_at       timestamp(6) with time zone not null,
    last_modified_at timestamp(6) with time zone not null
);
create index idx_cart_token on carts (token);
create index idx_cart_user_id on carts (user_id);
create index idx_cart_expires_at on carts (expires_at);

create table cart_ga_item
(
    id               bigint generated by default as identity primary key,
    cart_id          uuid                        not null
        constraint fk_cart_ga_item_cart references carts (id),
    session_id       uuid                        not null,
    ga_area_id       bigint                      not null
        constraint fk_cart_ga_item_area references chart_ga_areas (id),
    unit_price       numeric(10, 2)              not null,
    quantity         integer                     not null,
    created_at       timestamp(6) with time zone not null,
    last_modified_at timestamp(6) with time zone not null
);

create table cart_seats
(
    id               bigint generated by default as identity primary key,
    cart_id          uuid                        not null
        constraint fk_cart_seats_cart references carts (id),
    session_id       uuid                        not null,
    seat_id          bigint                      not null
        constraint fk_cart_seats_seat references chart_seats (id),
    unit_price       numeric(10, 2)              not null,
    created_at       timestamp(6) with time zone not null,
    last_modified_at timestamp(6) with time zone not null,
    constraint uk_cart_seat_session_seat unique (session_id, seat_id)
);

create table cart_tables
(
    id               bigint generated by default as identity primary key,
    cart_id          uuid                        not null
        constraint fk_cart_tables_cart references carts (id),
    session_id       uuid                        not null,
    table_id         bigint                      not null
        constraint fk_cart_tables_table references chart_tables (id),
    unit_price       numeric(10, 2)              not null,
    created_at       timestamp(6) with time zone not null,
    last_modified_at timestamp(6) with time zone not null,
    constraint uk_cart_table_session_table unique (session_id, table_id)
);

/* =========================================================
   10. Webhooks
   ========================================================= */

create table webhook_events
(
    id               uuid                        not null primary key,
    platform_id      uuid                        not null,
    event_type       varchar(50)                 not null check (event_type in
                                                                 ('SEAT_RESERVED', 'SEAT_RELEASED', 'SEAT_BOOKED',
                                                                  'BOOKING_CANCELLED', 'GA_AVAILABILITY_CHANGED',
                                                                  'SESSION_CONFIG_UPDATED')),
    session_id      uuid        not null,
    payload          text                        not null,
    seat_code       varchar(50),
    ga_area_code    varchar(50),
    table_code      varchar(50),
    status          varchar(20) not null check (status in ('PENDING', 'DELIVERED', 'FAILED')),
    response_code    integer,
    response_body    text,
    error_message    text,
    attempt_count    integer                     not null,
    next_retry_at    timestamp(6) with time zone,
    last_attempt_at timestamp(6) with time zone,
    created_at       timestamp(6) with time zone not null,
    last_modified_at timestamp(6) with time zone not null
);
create index idx_webhook_platform_id on webhook_events (platform_id);
create index idx_webhook_status on webhook_events (status);
create index idx_webhook_next_retry on webhook_events (next_retry_at);

/* =========================================================
   11. Payments
   ========================================================= */

CREATE TABLE payments
(
    id                 UUID PRIMARY KEY,
    booking_id         UUID                     NOT NULL,
    amount             DECIMAL(19, 2)           NOT NULL,
    currency           VARCHAR(3)               NOT NULL,
    status             VARCHAR(20)              NOT NULL,
    external_reference VARCHAR(255),
    merchant_id        UUID                     NOT NULL,
    provider_id VARCHAR(50) NOT NULL,
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at         TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_payment_booking_id ON payments (booking_id);
CREATE INDEX idx_payment_external_ref ON payments (external_reference);