-- =============================================================================
-- V6__Add_chart_landmarks.sql
-- Purpose: Add chart_landmarks table for non-bookable visual elements
-- =============================================================================
-- This migration adds support for static visual elements on seating charts
-- such as Stage, Exit, Bar, Restroom, etc. These are purely visual/structural
-- elements that help users orient themselves on the seating map.
-- =============================================================================

-- Create chart_landmarks table
CREATE TABLE chart_landmarks (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chart_id         UUID NOT NULL
        CONSTRAINT fk_landmarks_chart REFERENCES seating_charts(id) ON DELETE CASCADE,
    label            VARCHAR(100) NOT NULL,
    type             VARCHAR(50) NOT NULL
        CHECK (type IN ('STAGE', 'SCREEN', 'ENTRANCE', 'EXIT', 'BAR', 'RESTROOM', 'PILLAR', 'STAIRS', 'ELEVATOR', 'OTHER')),
    shape_type       VARCHAR(50) NOT NULL DEFAULT 'RECTANGLE'
        CHECK (shape_type IN ('RECTANGLE', 'CIRCLE', 'ELLIPSE', 'POLYGON', 'PATH', 'ICON')),
    x_position       DOUBLE PRECISION NOT NULL,
    y_position       DOUBLE PRECISION NOT NULL,
    width            DOUBLE PRECISION,
    height           DOUBLE PRECISION,
    rotation         DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    boundary_path    TEXT,
    icon_key         VARCHAR(100),
    created_at       TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    last_modified_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- Index for efficient chart lookups
CREATE INDEX idx_landmark_chart ON chart_landmarks(chart_id);

-- Add comment for documentation
COMMENT ON TABLE chart_landmarks IS 'Non-bookable visual elements on seating charts (Stage, Exit, Bar, etc.)';
COMMENT ON COLUMN chart_landmarks.type IS 'Semantic type for frontend icon/styling selection';
COMMENT ON COLUMN chart_landmarks.shape_type IS 'Geometric shape for rendering (RECTANGLE, CIRCLE, POLYGON, PATH, ICON)';
COMMENT ON COLUMN chart_landmarks.boundary_path IS 'SVG path data for complex shapes';
COMMENT ON COLUMN chart_landmarks.icon_key IS 'Reference to frontend icon library (e.g., "fa-martini-glass")';

-- Verification query (run after migration to validate)
-- SELECT COUNT(*) FROM chart_landmarks;
