spring.application.name=venues-api
spring.profiles.active=dev
spring.config.import=optional:file:.env[.properties]

# Logging pattern
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
# i18n
spring.messages.basename=messages
spring.messages.encoding=UTF-8
# JSON
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.serialization.indent-output=true
spring.jackson.deserialization.fail-on-unknown-properties=false
spring.jackson.default-property-inclusion=non_null
spring.jackson.time-zone=UTC