spring.application.name=ArmTick.am
spring.application.version=1.0.0
spring.profiles.active=dev
spring.config.import=optional:file:.env[.properties]
# SERVER CONFIGURATION (common)
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-exception=false

# Logging pattern
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# i18n
spring.messages.basename=messages
spring.messages.encoding=UTF-8
# JSON / Jackson
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.serialization.indent-output=true
spring.jackson.deserialization.fail-on-unknown-properties=false
spring.jackson.default-property-inclusion=non_null
spring.jackson.time-zone=UTC